version: "3.1"
services:
  node:
    image: node
    working_dir: /app
    # env_file: ./.env
    ports:
      - "80:3000"
      - "8000:8000"
      - "9005:9005"
    volumes:
      - app:/app
      - config:/root
    command: yarn start
volumes:
  app:
  config:
