version: 2.1
jobs:
  build:
    working_directory: ~/anilife-client
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
      - run:
          name: install packages
          command: yarn
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: firebase deploy
          command: node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
